#!/usr/bin/env bash
# Adapted from WATonomous/wato_f1tenth main at 4aa2c4a.
# Changes: repository/branch/user isolation and training-specific variables.

# Keep readable names while distinguishing e.g. feature/foo from feature-foo.
watod_name() {
    local original="$1" normalized digest
    normalized="$(printf '%s' "$original" | LC_ALL=C tr '[:upper:]' '[:lower:]' |
        LC_ALL=C tr -cs 'a-z0-9_-' '-' | sed 's/^-*//; s/-*$//')"
    normalized="${normalized:-unnamed}"
    if [[ "$normalized" != "$original" || ${#normalized} -gt 80 ]]; then
        digest="$(printf '%s' "$original" | sha256sum)"
        normalized="${normalized:0:80}-${digest:0:8}"
    fi
    printf '%s' "$normalized"
}

BRANCH="${BRANCH:-$(git -C "$MONO_DIR" branch --show-current)}"
if [[ -z "$BRANCH" ]]; then
    BRANCH="detached-$(git -C "$MONO_DIR" rev-parse --short HEAD)"
fi
REPO_SLUG="$(watod_name "$REPO_NAME")"
BRANCH_SLUG="$(watod_name "$BRANCH")"
USER_SLUG="$(watod_name "${USER:-$(id -un)}")"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-watod_${REPO_SLUG}_${BRANCH_SLUG}_${USER_SLUG}}"
TAG="$(watod_name "${TAG:-$BRANCH}")"
ROBOT_IMAGE="${ROBOT_IMAGE:-$REGISTRY_URL/robot}"
HOST_UID="${HOST_UID:-$(id -u)}"
HOST_GID="${HOST_GID:-$(id -g)}"
DATA_DIR="${DATA_DIR:-$MONO_DIR/src/data}"

if [[ -z "${PLATFORM:-}" ]]; then
    case "$(uname -m)" in
        x86_64|amd64) PLATFORM=amd64 ;;
        aarch64|arm64) PLATFORM=arm64 ;;
        *) printf 'Set PLATFORM to amd64 or arm64 for this host.\n' >&2; exit 1 ;;
    esac
fi
case "$PLATFORM" in
    amd64|arm64) ;;
    *) printf 'Unsupported PLATFORM: %s\n' "$PLATFORM" >&2; exit 1 ;;
esac
case "$MODE_OF_OPERATION" in
    develop|deploy) ;;
    *) printf 'MODE_OF_OPERATION must be develop or deploy.\n' >&2; exit 1 ;;
esac
case "$ENABLE_GPU" in
    true|1) ENABLE_GPU=true ;;
    false|0) ENABLE_GPU=false ;;
    *) printf 'ENABLE_GPU must be true or false.\n' >&2; exit 1 ;;
esac
if [[ ! "$COMPOSE_PROJECT_NAME" =~ ^[a-z0-9][a-z0-9_-]*$ ]]; then
    printf 'COMPOSE_PROJECT_NAME must be a lowercase Docker Compose name.\n' >&2
    exit 1
fi
if [[ ! "$HOST_UID" =~ ^[0-9]+$ || ! "$HOST_GID" =~ ^[0-9]+$ ]]; then
    printf 'HOST_UID and HOST_GID must be numeric.\n' >&2
    exit 1
fi
if [[ "$DATA_DIR" != /* || ! -d "$DATA_DIR" ]]; then
    printf 'DATA_DIR must be an existing absolute directory: %s\n' "$DATA_DIR" >&2
    exit 1
fi

# Compose reads this as an env file, not as an executable shell script.
# Single quotes preserve paths containing spaces or dollar signs.
{
    printf '# Generated by watod; edit watod-config.local.sh instead.\n'
    for name in MONO_DIR MODULES_DIR ACTIVE_MODULES MODE_OF_OPERATION \
        COMPOSE_PROJECT_NAME TAG PLATFORM ROBOT_IMAGE BASE_IMAGE_OVERRIDE \
        HOST_UID HOST_GID DATA_DIR ENABLE_GPU; do
        value="${!name}"
        value="${value//\'/\\\'}"
        printf "%s='%s'\n" "$name" "$value"
    done
} > "$MODULES_DIR/.env"
